name: miapp_cafeconecta
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_generative_ai: ^0.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutterfire_cli: ^1.1.0
  table_calendar: ^3.0.9
  intl: ^0.18.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/ui/screens/assets/images/logo.png
    
  uses-material-design: true


