// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLp92ig8WLBt7FhCOlgP8v4LiAEccOM8',
    appId: '1:831848720948:web:ebbc14fcaa6b4e8c23b861',
    messagingSenderId: '831848720948',
    projectId: 'cafeconnecta-6a858',
    authDomain: 'cafeconnecta-6a858.firebaseapp.com',
    storageBucket: 'cafeconnecta-6a858.firebasestorage.app',
    measurementId: 'G-WYDDD8RF6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5elKRGGggdOks_Ike_pBKV2SnyM6eB4',
    appId: '1:831848720948:android:fdc4cc7d5e4366ed23b861',
    messagingSenderId: '831848720948',
    projectId: 'cafeconnecta-6a858',
    storageBucket: 'cafeconnecta-6a858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQa6dwThS_zCjWojv9xZpqE54fWldg53U',
    appId: '1:831848720948:ios:f4594037ae23049023b861',
    messagingSenderId: '831848720948',
    projectId: 'cafeconnecta-6a858',
    storageBucket: 'cafeconnecta-6a858.firebasestorage.app',
    iosBundleId: 'com.example.CafeConecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQa6dwThS_zCjWojv9xZpqE54fWldg53U',
    appId: '1:831848720948:ios:96725fa658c5611923b861',
    messagingSenderId: '831848720948',
    projectId: 'cafeconnecta-6a858',
    storageBucket: 'cafeconnecta-6a858.firebasestorage.app',
    iosBundleId: 'com.example.miappCafeconecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvLp92ig8WLBt7FhCOlgP8v4LiAEccOM8',
    appId: '1:831848720948:web:6415d9829fea5ffe23b861',
    messagingSenderId: '831848720948',
    projectId: 'cafeconnecta-6a858',
    authDomain: 'cafeconnecta-6a858.firebaseapp.com',
    storageBucket: 'cafeconnecta-6a858.firebasestorage.app',
    measurementId: 'G-SJ7DYJ1R8T',
  );
}
